theme = "catppuccin_macchiato"
# theme = "carbon"

[editor]
color-modes = true
true-color = true
auto-format = true
mouse = false
bufferline = "always"
auto-save = true

[editor.statusline]
right = ["version-control", "diagnostics", "selections", "register", "position", "file-encoding"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
Y = ":clipboard-yank"
C-h = ":buffer-previous"
C-j = ["page_cursor_half_down", "align_view_center"]
C-k = ["page_cursor_half_up", "align_view_center"]
C-l = ":buffer-next"
esc = ["collapse_selection", "keep_primary_selection"]
C-w = ":buffer-close"
C-r = [":reload-all", ":lsp-restart"]
D = "kill_to_line_end"

# "more sane" version of existing functionality
# x = ["goto_line_start", "select_mode", "goto_line_end_newline"]

# for moving selected lines up/down
C-A-j = ['ensure_selections_forward', 'extend_to_line_bounds', 'extend_char_right', 'extend_char_left', 'delete_selection', 'add_newline_below', 'move_line_down', 'replace_with_yanked']
C-A-k = ['ensure_selections_forward', 'extend_to_line_bounds', 'extend_char_right', 'extend_char_left', 'delete_selection', 'move_line_up', 'add_newline_above', 'move_line_up', 'replace_with_yanked']

# these are reversed from their defaults
d = "delete_selection_noyank"
A-d = "delete_selection"
c = "change_selection_noyank"
A-c = "change_selection"
########################################

[keys.select]
# Copy/yank related shortcuts to match normal mode
Y = ":clipboard-yank"
d = "delete_selection_noyank"
A-d = "delete_selection"
c = "change_selection_noyank"
A-c = "change_selection"
