[[language]]
name = "ruby"
formatter = { command = "bundle", args = [ "exec", "stree", "format" ]}
auto-format = true

[[language]]
name = "elixir"
auto-format = true

[[language]]
name = "jsx"
auto-format = true

[[language]]
name = "erb"

[language.auto-pairs]
'<' = '>'
'%' = '%'
"'" = "'"
'"' = '"'
