[[language]]
name = "ruby"
formatter = { command = "bundle", args = [ "exec", "stree", "format" ]}
auto-format = true

[language-server.solargraph.config.solargraph]
diagnostics = true

[[language]]
name = "elixir"
auto-format = true

[[language]]
name = "jsx"
auto-format = true

[[language]]
name = "erb"
file-types = ["erb", "html"]
language-servers = [ "tailwindcss-ls" ]

[language.auto-pairs]
'<' = '>'
'%' = '%'
"'" = "'"
'"' = '"'
