[[language]]
name = "ruby"
auto-format = true
config = { solargraph = { diagnostics = true, formatting = false } }
formatter = { command = "bundle", args = ["exec", "stree", "format"] }

[[language]]
name = "elixir"
auto-format = true
